### ISSUE TITLE
iOS13 release version not working

### ISSUE THREAD

**Issue by luzsyn** [HackingGate/iOS13-WiFi-Info#7] opened 2019-09-23 12:54 UTC
In some devices still not working, CNCopySupportedInterfaces() return nil, already get the location authorization, very strange

**Comment by Benny-iPhone** [comment] 2019-09-23 14:45
#me_too

**Comment by kendgin** [comment] 2019-09-24 03:01
me too

**Comment by fanwu8184** [comment] 2019-09-24 06:55
same here. Any solution?

**Comment by HackingGate** [comment] 2019-09-24 07:02
Hi all,
Couldn't reproduce it on iOS 13.1 beta 4.
Is it happens on iOS 13.0 final release?
Please provide more details.

**Comment by fanwu8184** [comment] 2019-09-24 07:04
Yes, I am working on iOS 13.0

**Comment by Benny-iPhone** [comment] 2019-09-24 07:07
Yes, I am working on iOS 13.0.
Installed the app from both Xcode 10.3 and Xcode 11

**Comment by luzsyn** [comment] 2019-09-24 07:10
It happens on iOS 13.0 final release and in some devices. Before 13.0 the code works, but not working after update to 13.0. Accounting to the user's feedback, CNCopySupportedInterfaces() return nil.(Already access loaction permission)

**Comment by kendgin** [comment] 2019-09-24 07:27
Before 13.0 the code works, but not working after update to 13.0 final release. CNCopySupportedInterfaces() return nil.(Already access loaction permission)
The problem solved after updating my phone to iOS 13.1 now.

**Comment by platinum7919** [comment] 2019-09-24 15:10
Same here. 
- Has location service enabled and allowed
- Has Access Wifi entitlement

**Comment by fanwu8184** [comment] 2019-09-25 01:14
The problem solved after updating my phone to iOS 13.1 which you can download now.

**Comment by barunkn10** [comment] 2019-09-25 04:07
No, this is not working in iOS 13.1. CNCopyCurrentNetworkInfo is returning NIL

private func updateSSID() -> String? {
            guard let interfaceNames = CNCopySupportedInterfaces() as? [String] else {
                return nil
            }

            return interfaceNames.compactMap { name in
                guard let info = CNCopyCurrentNetworkInfo(name as CFString) as? [String: AnyObject], let ssid = info[kCNNetworkInfoKeySSID as String] as? String else {
                    return nil
                }
                return ssid
            }
            .filter({ (ssid) -> Bool in
                !ssid.isEmpty
                }
            )
            .first ?? nil
        }

**Comment by fanwu8184** [comment] 2019-09-25 04:18
- Has location service enabled and allowed
- Has Access Wifi entitlement

Did you make sure of these?

**Comment by barunkn10** [comment] 2019-09-25 04:20
Yes, I did. 

Below, check is successful for me - 
let status = CLLocationManager.authorizationStatus()
  if status == .authorizedWhenInUse {
...
}

**Comment by barunkn10** [comment] 2019-09-25 04:21
also, 
<key>com.apple.developer.networking.wifi-info</key>
	<true/>

**Comment by barunkn10** [comment] 2019-09-25 04:21
<key>com.apple.developer.networking.wifi-info</key>
	<true/>

**Comment by fanwu8184** [comment] 2019-09-25 04:32
It works fine to me by using HackingGate's code below:

import Foundation
import SystemConfiguration.CaptiveNetwork

func getSSID() -> String? {
    var ssid: String?
    if let interfaces = CNCopySupportedInterfaces() as NSArray? {
        for interface in interfaces {
            if let interfaceInfo = CNCopyCurrentNetworkInfo(interface as! CFString) as NSDictionary? {
                ssid = interfaceInfo[kCNNetworkInfoKeySSID as String] as? String
                break
            }
        }
    }
    return ssid
}

**Comment by barunkn10** [comment] 2019-09-25 04:46
Thanks for the info. However, interfaceInfo in below code is still returning nil for me.
 
let interfaceInfo = CNCopyCurrentNetworkInfo(interface as! CFString) as NSDictionary?

**Comment by PadrePedro** [comment] 2019-09-25 05:48
Working for me, but I have users for whom it does not work, even after granting location permissions.  I haven't been able to determine why.

**Comment by platinum7919** [comment] 2019-09-25 06:40
Works for me this morning, but not anymore. This is very strange. Same code.
- Works for 12.4.1
- Doesn't work for 13.0
- Worked once in 13.1 (same build)
- Has entitlement
- Has location permission

Edit: (on 13.1)
When it doesn't work, I restart the device then launch the app again then it works.
When it doesn't work, The location indicator (array) is always on (sometime hollow).

Seems like it will only work for a few minutes after launch

Edit:
After the 3rd device restart it now works with no problem

**Comment by PadrePedro** [comment] 2019-09-26 00:20
I encountered one iOS 13.1 device where CNCopyCurrentNetworkInfo always returned nil.  After rebooting the device, it started working!  Can you guys try rebooting?  I'm trying it figure out if rebooting is a possible workaround, or just a fluke.  Thanks.

PS: I also filed a bug with Apple.

**Comment by barunkn10** [comment] 2019-09-26 03:54
(1) It seems to me, the location permission value is getting wiped out (Apple internal issue?). So, if we go manually and turn location service for our app is equal to "Always" ( in iOS 13, Apple has stopped programmatically setting permission value as "Always"). Then, I am getting SSID value all the time.

(2) Restart of device is also solving issue in few cases.

**Comment by oflannabhra** [comment] 2019-10-03 15:28
Like others, I am getting reports from users that even after they have granted location permissions, my app still thinks they are not connected to WiFi (ie, `CNCopyCurrentNetworkInfo` returns `nil`). I have reports of this across:
- 13.0
- 13.1
- 13.1.1
- 13.1.2

Updating to a new version seems to fix the issue, at least for some users.

Has anyone filed a radar with Apple? If so, could you link here?

**Comment by PadrePedro** [comment] 2019-10-03 23:26
I have filed a bug with Apple.   They said the sysdiagnose logs I provided did not include the call to CNCopyCurrentNetworkInfo.  Unfortunately, I restarted that iPhone and it no longer exhibits the issue, so I'm looking for another phone to capture the logs.

So far, I am aware of 3 iPhones with this issue, and all 3 were resolved with a restart.

**Comment by Raphzz** [comment] 2019-10-04 14:35
Faced this same issue today. We have 2 QA devices updated to 13.1.2, on one it worked fine and the other required 2 reboots to work as well.

**Comment by mrsnk** [comment] 2019-10-08 06:48
同样的问题，还没解决

**Comment by mrsnk** [comment] 2019-10-08 07:11
+1

**Comment by james-flume** [comment] 2019-10-10 23:23
Any updates on this?

**Comment by PadrePedro** [comment] 2019-10-11 00:12
I found another phone with this issue, captured logs again and provided to Apple on 10/9.  Waiting for response.

**Comment by james-flume** [comment] 2019-10-11 00:19
Thanks @PadrePedro , keep us posted

**Comment by eklektek** [comment] 2019-10-12 15:39
I found that it worked, but only once for each app instance.
So if I changed network while my app was running, on returning to the foreground there was no location update and the new network wasn't registered by the app. Had to close and re-open. On 13.1.2

**Comment by Ricardo1980** [comment] 2019-10-18 11:31
Same problem in iOS 13.1.3

**Comment by luzsyn** [comment] 2019-10-24 04:08
Very unstable, some users updated the newest system version, it works some days, but from yesterday, it doesn`t works. 
@PadrePedro Do you have receive response from Apple?

**Comment by kevin3747118** [comment] 2019-10-25 07:43
After the device rebooting, it works...also make me embarrassed during the demo. 
iOS13.1.2

**Comment by Ricardo1980** [comment] 2019-10-25 08:14
Kevin, it will start failing 2 or 3 after rebooting. At least that is my case.

**Comment by kevin3747118** [comment] 2019-10-25 08:15
@Ricardo1980 Do you mean that it will fail at the first time ? what's your iOS version ?

**Comment by Ricardo1980** [comment] 2019-10-25 08:30
I am using 13.2
It will work for several hours. After that, it does not work. That is my case.

**Comment by PadrePedro** [comment] 2019-10-28 16:16
> Very unstable, some users updated the newest system version, it works some days, but from yesterday, it doesn`t works.
> @PadrePedro Do you have receive response from Apple?

Nothing from Apple since I submitted logs on 10/9.  I requested status update on 10/23, but still nothing.

**Comment by james-flume** [comment] 2019-10-28 16:58
@PadrePedro is there a ticket open somewhere on apple that we can contribute to? I have observed the same behavior as everyone in this thread.

**Comment by shanez** [comment] 2019-11-04 18:47
@james-flume We can solve this by doing an IP address comparison.  The risk here is relative to the amount of routers that may use that IP address as their default AP mode address.  Even given this risk, it seems to be the best path forward.

**Comment by PadrePedro** [comment] 2019-11-05 20:10
> @PadrePedro is there a ticket open somewhere on apple that we can contribute to? I have observed the same behavior as everyone in this thread.

The ticket I opened is through Apple's Feedback Assistant.  There has been no reply to this issue from Apple since Oct 9th.  I tried to escalate the issue via Apple Developer Technical Support, but they referred me back to Feedback Assistant.  It is not a public forum so I have no way to share the thread.

**Comment by PadrePedro** [comment] 2019-11-06 06:24
Good news!  I was contacted by Apple today to test out the fix for this issue on iOS 13.3 beta 1 (17C5032d).  Test away!

**Comment by inf3rnus** [comment] 2019-11-08 22:21
I've been spending months trying to fix my code, and low and behold we've discovered it's a bug... @PadrePedro Thank you for your efforts, they're invaluable.

So I guess we're all just dead in the water until Apple gets their fix in place?

**Comment by kcchen2012** [comment] 2019-11-27 00:56
We also have some customers to report the issue exists on their devices, still can't find a perfect resolution.

**Comment by james-flume** [comment] 2019-11-27 01:09
@kcchen2012 we started using [FGRoute](https://github.com/Feghal/FGRoute) instead of the native wifi Interfaces and have not seen the issue since.

**Comment by kcchen2012** [comment] 2019-11-27 02:19
> @kcchen2012 we started using [FGRoute](https://github.com/Feghal/FGRoute) instead of the native wifi Interfaces and have not seen the issue since.

thanks for your reply.

**Comment by platinum7919** [comment] 2019-12-01 03:06
I tried FGRoute, but I still have the same issue. It returns nil

**Comment by vadzimrudkouski** [comment] 2019-12-10 22:52
> Good news! I was contacted by Apple today to test out the fix for this issue on iOS 13.3 beta 1 (17C5032d). Test away!

I wonder whether anyone reproduced the issue on iOS 13.3.

**Comment by nneuberger1** [comment] 2019-12-18 06:34
After installing the 13.3 GM release, I was able to get the command to work fine by this github page.

I was also able to get the FGRoute pod to work fine except for the FGRoute.getSSIDDATA() function as it's causing my application to crash, although I don't need that function.

https://github.com/Feghal/FGRoute

**Comment by Feghal** [comment] 2019-12-18 07:18
Hello everyone, I am the FGRoute maintainer, just tested on iOS 13.3 with Xcode 11.1 and it works fine, I think it may be related to Xcode version, what version do you use?

**Comment by nneuberger1** [comment] 2019-12-19 01:27
FWIW, I was using XCode 11.2.1 and iOS 13.1 variant (I think roughly) when I found the issue. Running 11 SDK minimum compilation.

**Comment by HackingGate** [comment] 2020-01-29 06:34
The issue is not reproducible on iOS 13.3. Closing.

**Closed as completed by HackingGate** 2020-01-29 06:34 UTC

**Comment by qianlishun** [comment] 2020-04-22 06:07
This still exists in iOS 13.3,  iPad mini4

CNCopySupportedInterfaces() is nil.
 
And Using NEHotspotConfigurationManager will throw
`NEHotspotConfigurationManager Error Domain=NEHotspotConfigurationErrorDomain Code=13 "already associated."  `

In IOS 13.1 13.2,  Code=8 " internal error ”


I rebooted the device many times in an hour and repeated the problem.

**Comment by qianlishun** [comment] 2020-04-22 09:18
> @kcchen2012 we started using [FGRoute](https://github.com/Feghal/FGRoute) instead of the native wifi Interfaces and have not seen the issue since.

The principle of getting SSID is the same, use CNCopySupportedInterfaces(). 

What makes you think another one can solve the problem

**Comment by Glumelin** [comment] 2020-06-29 04:21
我在设备iPhone 6s Plus，iOS 13.5.1 中复现了
